apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: gmrp/bd
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deploy
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
        - name: backend
          image: gmrp/usergke
          env:
          - name: MYSQL_HOST 
            value: service-mysql
          - name: MYSQL_USER 
            value: gilda
          - name: MYSQL_PASSWORD 
            value: gilda
          - name: MYSQL_DATABASE 
            value: user
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    app: backend-deploy
spec:
  type: LoadBalancer
  selector:
    app: backend-deploy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP